# Generated by Django 3.2.9 on 2021-11-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='Image/None/img.jpg', upload_to='media'),
        ),
    ]
